TRUNCATE TABLE pns_data CASCADE;
TRUNCATE TABLE ort_data CASCADE;
TRUNCATE TABLE parameter_data CASCADE;
TRUNCATE TABLE featureofinterest CASCADE;
TRUNCATE TABLE featurerelation CASCADE;
TRUNCATE TABLE observableproperty CASCADE;
TRUNCATE TABLE probe CASCADE;